version: '3.9'
name: "pals"
volumes:
  mongo:
    name: mongo-persistent
  web-app-build:
    name: pals-build-directory
services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
      MONGO_INITDB_DATABASE: ${MONDO_DB}
      MONGO_INITDB_USER: ${MONGO_USER}
      MONGO_INITDB_PWD: ${MONGO_PWD}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - mongo:/data/db
  mongo-express:
    container_name: mongo-exress
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PWD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ADMIN_USER}:${MONGO_PWD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  web-app:
    container_name: pals-web-app
    build:
      context: ./web-app
      dockerfile: Dockerfile
    image: pals-web-app
    env_file: .env
    ports:
      - "3000:3000"
    # volumes:
    #   - web-app-build:/app
  server-app:
    container_name: pals-server-app
    build:
      context: ./server-app
      dockerfile: Dockerfile
    image: pals-server-app
    env_file: .env
    ports:
      - "8080:8080"
